### PR TITLE
Major rewrite

### PR DESCRIPTION
**Pull request by KatieFrogs**
I removed like everything
Probably still works idk
- [x] Added a userscript icon, pls rate
- [x] Removed the former post form completely, u can use either original post form (at the top of the page when u click on the Original Form button) or 4chan-X quick reply instead
- [x] Did not add threading support yet sry
- [x] Will probably add native extension QR too someday

The `element()` function might be a little confusing to u, sry in advance
— kekero

### CODE REVIEW

**Comment by doctorwth** [comment]
Thank you, javascript wizard. and the icon is also beautiful.

It breaks in my instance of Firefox with `GM_xmlhttpRequest is not defined`. Did a google and apparently Greasemonkey updated their API recently so it's `GM.xmlHttpRequest`. Tested it with changing the grant permission and the call to the updated version and it works in Firefox with greasemonkey and chromium with tampermonkey.

the CSS doesn't load in Chromium with tampermonkey

>Removed the former post form completely, u can use either original post form (at the top of the page when u click on the Original Form button) or 4chan-X quick reply instead

We can't rely on the original post form because it's gone when threads are archived and will prevent non 4chan-x users from posting then, which has become an unintended feature.

I've sent you an invite link so you can contribute directly to the main repo and it'll be easier for both us to make changes. pls branch off dev instead of master for contributions :^)

**Comment by KatieFrogs** [comment]
Tnx for testing it, I have added compatibility with Greasemonkey and Chromium
Added native extension's quick reply support
The original post form now always appears in archived threads, it is still at the top though

**Comment by KatieFrogs** [comment]
Did everything I wanted to add, it is ready to merge unless u want me to create a new pull request to merge it to another branch

**Comment by doctorwth** [comment]
slick as fugg
ty for your hardwork

**Pull request merged**
